sudo: required
services:
  - docker

before_install:
  - docker build -t raphsmart/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raphsmart/react-test npm test -- --coverage
 # - docker run -e CI=true raphsmart/react-test npm test
after_success:
  - docker build -t raphsmart/multi-client ./client
  - docker build -t raphsmart/multi-nginx ./nginx
  - docker build -t raphsmart/multi-server ./server
  - docker build -t raphsmart/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push raphsmart/multi-client
  - docker push raphsmart/multi-nginx
  - docker push raphsmart/multi-server
  - docker push raphsmart/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: "multi-docker"
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-795569145762'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY