sudo: required
services:
  - docker

before_install:
  - docker build -t raphsmart/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raphsmart/react-test npm test -- --coverage
 # - docker run -e CI=true raphsmart/react-test npm test
after_success:
  - docker build -t raphsmart/multi-client ./client
  - docker build -t raphsmart/multi-nginx ./nginx
  - docker build -t raphsmart/multi-server ./server
  - docker build -t raphsmart/multi-worker ./worker
